global:
  env:

appConfig:
  appName: contact-lists
  replicas: 1
  image: tcr.tks.trueidc.com/portal/gcp-backend
  tag: v0.0.1
  imagePullPolicy: IfNotPresent
  imagePullSecretsName: regcred
  imagePullSecretsSource: 
    create: false
    name: regcred
    registry: https://ghcr.io/techguys-tidc/online-contact
    username: 
    password: 
  containerPort: 8080
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  environments:
    

