global:
  env:

appConfig:
  appName: contact-lists
  replicas: 1
  image: ghcr.io/techguys-tidc/online-contact
  tag: v0.0.2
  imagePullPolicy: IfNotPresent
  imagePullSecretsName: regcred
  imagePullSecretsSource: 
    create: true
    name: regcred
    registry: ghcr.io/techguys-tidc/online-contact
    username: 
    password: 
  containerPort: 8080
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  environments: