apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "contact-lists.labels" . | indent 4 }}
    app: {{ .Values.appConfig.appName }}-{{ .Values.global.env }}-api
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
  name: {{ .Values.appConfig.appName }}-{{ .Values.global.env }}-api
spec:
  replicas: {{ .Values.appConfig.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appConfig.appName }}-{{ .Values.global.env }}-api
  template:
    metadata:
      labels:
        app: {{ .Values.appConfig.appName }}-{{ .Values.global.env }}-api
    spec:
      {{- if .Values.appConfig.imagePullSecretsSource.create }}
      imagePullSecrets:
      - name: {{ .Values.appConfig.imagePullSecretsSource.name }}
      {{- else }}
      imagePullSecrets:
      - name: {{ .Values.appConfig.imagePullSecretsName }}
      {{- end }}
      containers:
      - env:
        - name: env
          value: {{ .Values.global.env }}
        {{- range $key, $value :=  .Values.appConfig.environments }}
        - name: {{ $key }}
          value: {{ tpl $value $ }}
        {{- end }}
        image: {{ .Values.appConfig.image}}:{{ .Values.appConfig.tag  }}
        imagePullPolicy: {{ .Values.appConfig.imagePullPolicy}}
        name: {{ .Values.appConfig.appName }}-{{ .Values.global.env }}-api
        ports:
        - containerPort: {{ .Values.appConfig.containerPort }}
          protocol: TCP
        resources:
{{ toYaml .Values.appConfig.resources | indent 10 }}