{{ if and .Values.appConfig.imagePullSecretsSource.name .Values.appConfig.imagePullSecretsSource.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appConfig.imagePullSecretsSource.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "contact-lists.regcred" . }}
{{- end }}